##################################################
# Run Mr Coxall's Super Linter against code base #
##################################################

---
  name: Mr Coxall's Super Linter
      
  on: [push, pull_request]
      
  jobs:
    run-linters:
      name: Mr Coxall's Super Linter
      runs-on: ubuntu-latest
      
      steps:
        - name: Check out Git repository ðŸš¦
          uses: actions/checkout@main
  
        - name: Run GitHub Super Linter ðŸš€
          uses: github/super-linter@main
          env:
            VALIDATE_ALL_CODEBASE: true
            LINTER_RULES_PATH: /
            FILTER_REGEX_EXCLUDE: ./tsconfig.json
            VALIDATE_CLANG_FORMAT: false
            VALIDATE_JAVASCRIPT_STANDARD: false
            VALIDATE_PYTHON_FLAKE8: false
            VALIDATE_GITLEAKS: false # for secrets detection
            VALIDATE_JSCPD: false # for copy and paste detection
            DEFAULT_BRANCH: main
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}